disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Clarice Hong"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "January 2 2006"
description = "Clarice Hong's portofolio"
author = { headline = "Computational biologist @ MIT" }
